---
services:
  rflood:
    image: ghcr.io/hotio/rflood
    container_name: rflood
    volumes:
      - "{{ appdata_path }}/downloaders/rflood:{{ container_config_path }}"
      - /tank:/data
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
      - FLOOD_AUTH=false