---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - "{{ appdata_path }}/arrs/prowlarr:{{ container_config_path }}"
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped