---
services:
  qbitmanage:
    image: ghcr.io/hotio/qbitmanage
    container_name: qbitmanage
    volumes:
      - "{{ appdata_path }}/downloaders/qbitmanage:{{ container_config_path }}"
      - "{{ storage_path }}/torrents:{{ container_data_path }}/torrents"
      - "{{ appdata_path }}/downloaders/qbittorrent/data/BT_backup:/BT_backup"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
      - QBT_RUN=true
      - QBT_SCHEDULE=1440
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=true
      - QBT_REM_ORPHANED=true
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=true
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=true
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
      - QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE=true