---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - "{{ appdata_path }}/arrs/radarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped