---
galaxy_info:
  author: Your Name
  description: TrueNAS configuration and management role
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: TrueNAS
      versions:
        - all
  galaxy_tags:
    - truenas
    - storage
    - nas
    - freenas
    - system
    - configuration

  collections:
    - community.general
    - ansible.builtin

dependencies: []