---
- name: Configure Nginx for PXE
  ansible.builtin.template:
    src: nginx-pxe.conf.j2
    dest: /etc/nginx/conf.d/pxe.conf
    mode: '0644'
  notify: reload_nginx

- name: Copy iPXE menu file
  ansible.builtin.copy:
    src: "{{ pxe_server_menu }}"
    dest: "{{ pxe_server_http_root }}/{{ pxe_server_menu }}"
    mode: '0644'
