---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ pxe_server_packages }}"
    state: present
    update_cache: true

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop: "{{ pxe_server_directories }}"

- name: Ensure preseed directory exists
  ansible.builtin.file:
    path: "{{ pxe_server_http_root }}/preseed"
    state: directory
    mode: '0755'
    owner: root
    group: root
