galaxy_info:
  author: Ken Petro
  description: Proxmox post-installation setup
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - proxmox
    - virtualization
    - system
    - pve
    - debian

  namespace: kenpetro

dependencies: []
