---
# Tasks for configuring PCI passthrough

- name: Enable kernel modules for PCI passthrough
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "{{ item }}"
    state: present
  with_items: "{{ proxmox_pci_passthrough_passthrough_modules }}"
  when: proxmox_pci_passthrough_enable_passthrough | bool

- name: Add kernel parameters for IOMMU
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ proxmox_pci_passthrough_iommu_parameters }}"'
  when: proxmox_pci_passthrough_enable_passthrough | bool

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  args:
    creates: /boot/grub/grub.cfg
  when: proxmox_pci_passthrough_enable_passthrough | bool and not ansible_check_mode
