build-noble:
	packer build  -var-file='credentials.pkr.hcl' ./ubuntu-server-noble/ubuntu-server-noble.pkr.hcl

build-opnsense:
	packer build ./opnsense

valid-opnsense:
	packer validate ./opnsense

build-truenas:
	packer build ./truenas

valid-truenas:
	packer validate ./truenas