build-noble:
	packer build  -var-file='credentials.pkr.hcl' ./ubuntu-server-noble/ubuntu-server-noble.pkr.hcl

build-opnsense:
	packer build ./opnsense

valid-opnsense:
	packer validate ./opnsense

build-truenas24:
	packer build ./truenas-24.10

valid-truenas24:
	packer validate ./truenas-24.10

build-truenas25:
	packer build ./truenas-25.04

valid-truenas25:
	packer validate ./truenas-25.04	