---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    tags-ignore:
      - '**'
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - distro: ubuntu2204
            mode: github_releases
          - distro: ubuntu2204
            mode: package_manager
          - distro: ubuntu2004
            mode: github_releases
          - distro: ubuntu2004
            mode: package_manager
          - distro: debian12
            mode: github_releases
          - distro: debian12
            mode: package_manager
          - distro: debian11
            mode: github_releases
          - distro: debian11
            mode: package_manager
          - distro: rockylinux8
            mode: github_releases
          - distro: rockylinux9
            mode: github_releases
          - distro: fedora39
            mode: github_releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run molecule tests
        env:
          MOLECULE_DISTRO: ${{ matrix.config.distro }}
          INSTALL_MODE: ${{ matrix.config.mode }}
        run: molecule -v test
