---

- name: Install test-server
  become: true
  hosts: 192.168.2.249
  # roles:
  #    - role: tigattack.mergerfs
  # vars:
  #    mergerfs_mounts:
  #        - path: /mnt/media
  #          branches: /mnt/data*
  #          options: defaults,nonempty,allow_other,use_ino

  tasks:
    # Create Users & Groups
      - name: Create plex User
        ansible.builtin.user:
            name: plex
            comment: Plex User-MatchID on Plex server
            uid: 997
            create_home: false
            password: !

      - name: Ensure group "plex" exists with correct gid
        ansible.builtin.group:
            name: plex
            state: present
            gid: 997

      - name: Create Media User
        ansible.builtin.user:
            name: media
            comment: Media User
            create_home: false
            password: $6$moRTU8CvTEUDwaPF$JB6sqi.gAvBWytOBZYw7nDbRH220.ar.Hi9Y61ET4GSB3WQ4TBDUrVsg5bTp/Bjmw1oa8OAn1kNhF3Xwh4lcE1

      - name: Add pofo14 to Media Groups (need to add docker and rom users later)
        ansible.builtin.user:
            name: pofo14
            append: true
            groups: media

      - name: Create Paritions & FileSystems
        community.general.parted:
            device: /dev/sdb
            number: 1
            state: present

      - name: Create a ext4 filesystem on /dev/sdb1
        community.general.filesystem:
            fstype: ext4
            dev: /dev/sdb1

      - name: Mount Disk 1
        ansible.posix.mount:
            fstype: ext4
            src: /dev/sdb1
            path: /mnt/disk1
            state: mounted

      - name: Create Paritions & FileSystems
        community.general.parted:
            device: /dev/sdc
            number: 1
            state: present

      - name: Create a ext4 filesystem on /dev/sdc1
        community.general.filesystem:
            fstype: ext4
            dev: /dev/sdc1

      - name: Mount Disk 2
        ansible.posix.mount:
            fstype: ext4
            src: /dev/sdc1
            path: /mnt/disk2
            state: mounted

      - name: Create Paritions & FileSystems
        community.general.parted:
            device: /dev/sdd
            number: 1
            state: present

      - name: Create a ext4 filesystem on /dev/sdb1
        community.general.filesystem:
            fstype: ext4
            dev: /dev/sdd1

      - name: Mount Disk 3
        ansible.posix.mount:
            fstype: ext4
            src: /dev/sdd1
            path: /mnt/disk3
            state: mounted

      - name: Create Mount Data Directories
        ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            group: media
            owner: pofo14
            mode: '0775'
        loop:
            - /mnt/media
            - /mnt/disk1
            - /mnt/disk2
            - /mnt/disk3

      - name: Install MergerFS
        ansible.builtin.include_role:
            name: tigattack.mergerfs
        vars:
            mergerfs_mounts:
                - path: /mnt/data
                  branches:
                      - /mnt/disk*
                  # options: defaults,nonempty,allow_other,use_ino
                  options: >
                    defaults,nonempty,allow_other,use_ino,cache.files=partial,ignorepponrename=true,moveonenospc=true,dropcacheonclose=true,minfreespace=100G,func.getattr=newest,category.create=mfs,fsname=mergerfs

      - name: Install NFS
        ansible.builtin.include_role:
            name: geerlingguy.nfs
        vars:
            nfs_exports: ["/mnt/data/media/ *(fsid=0,rw,no_subtree_check)"]

      - name: Install Docker
        ansible.builtin.include_role:
            name: geerlingguy.docker
        vars:
            docker_users:
                - pofo14
