---

- name: Install test-server
  become: true
  hosts: 192.168.2.249
  # roles:
  #    - role: tigattack.mergerfs
  # vars:
  #    mergerfs_mounts:
  #        - path: /mnt/media
  #          branches: /mnt/data*
  #          options: defaults,nonempty,allow_other,use_ino

  tasks:
    # Create Users & Groups
      - name: Create plex User
        ansible.builtin.user:
            name: plex
            comment: Plex User-MatchID on Plex server
            uid: 997
            create_home: false
            password: !

      - name: Ensure group "plex" exists with correct gid
        ansible.builtin.group:
            name: plex
            state: present
            gid: 997

      - name: Create Media User
        ansible.builtin.user:
            name: media
            comment: Media User
            create_home: false
            password: $6$moRTU8CvTEUDwaPF$JB6sqi.gAvBWytOBZYw7nDbRH220.ar.Hi9Y61ET4GSB3WQ4TBDUrVsg5bTp/Bjmw1oa8OAn1kNhF3Xwh4lcE1

      - name: Add pofo14 to Media Groups (need to add docker and rom users later)
        ansible.builtin.user:
            name: pofo14
            append: true
            groups: media

      - name: Create Mount Data Directories
        ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            group: media
            owner: pofo14
            mode: '0775'
        loop:
            - /mnt/media
            - /mnt/data1
            - /mnt/data2
            - /mnt/data3

      - name: Install MergerFS
        ansible.builtin.include_role:
            name: tigattack.mergerfs
        vars:
            mergerfs_mounts:
                - path: /mnt/media
                  branches:
                      - /mnt/data*
                  # options: defaults,nonempty,allow_other,use_ino
                  options: >
                    defaults,nonempty,allow_other,use_ino,cache.files=partial,ignorepponrename=true,moveonenospc=true,dropcacheonclose=true,minfreespace=100G,func.getattr=newest,category.create=mfs,fsname=mergerfs
