---
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # If tests fail in one image, we still want the others to carry on running
      matrix:
        image:
          - geerlingguy/docker-debian12-ansible # bookworm (stable)
          - geerlingguy/docker-debian11-ansible # bullseye (oldstable)
          - geerlingguy/docker-debian10-ansible # buster (oldoldstable)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        env:
          IMAGE: ${{ matrix.image }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - lint
      - molecule
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Publish
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
