# Stage environment SOPS configuration
keys:
  - age_key_file: /home/pofo14/dev/IaC/terraform/key.txt
creation_rules:
  - path_regex: secrets\.enc\.yml$
    age: age1uhhg4yltp5et92fnvf5lwksq3u8d0tlw2mq7qq82vjl8z8wh3v0q8ux9gs
  # Stage-specific rules can be added here
  # - path_regex: .*stage.*\.yml$
  #   age: stage_specific_key
