---
services:
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    volumes:
      - "{{ appdata_path }}/downloaders/sabnzb:{{ container_config_path }}"
      - "{{ storage_path }}/usenet:{{ container_data_path }}/usenet"
    ports:
      - 8081:8080
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always