# geerlingguy.docker
docker_edition: 'ce'
docker_packages_state: present
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present
docker_add_repo: false
docker_users:
  - pofo14

# ironicbadger.docker-compose-generator
# global vars
global_env_vars:
  - "PUID=1000"
  - "PGID=1001"
  - "TZ=America/New_York"

docker_compose_generator_output_path: "/home/pofo14"
appdata_path: /opt/appdata
storage_path: /mnt/data
container_config_path: /config
container_data_path: /data

containers:
  ### Arrs
  ###
  - service_name: radarr
    active: true
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/radarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 7878:7878
    restart: unless-stopped

  - service_name: sonarr
    active: true
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/sonarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 8989:8989
    restart: unless-stopped

  - service_name: prowlarr
    active: true
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/prowlarr:{{ container_config_path }}"
    ports:
      - 9696:9696
    restart: unless-stopped

  ### Download Apps
  ###
  - service_name: deluge
    active: true
    image: lscr.io/linuxserver/deluge:latest
    volumes:
      - "{{ appdata_path }}/downloaders/deluge:{{ container_config_path }}"
      - /tank:/roms
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: always

  - service_name: qbittorrent
    active: true
    image: ghcr.io/hotio/qbittorrent
    volumes:
      - "{{ appdata_path }}/downloaders/qbittorrent:{{ container_config_path }}"
      - "{{ storage_path }}/torrents:{{ container_data_path }}/torrents"
      - /tank:/roms
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always

  - service_name: sabnzbd
    active: true
    image: ghcr.io/hotio/sabnzbd
    volumes:
      - "{{ appdata_path }}/downloaders/sabnzb:{{ container_config_path }}"
      - "{{ storage_path }}/usenet:{{ container_data_path }}/usenet"
    ports:
      - "8081:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always


## Snapraid settings

snapraid_config_excludes:
  - '*.unrecoverable'
  - /tmp/
  - /lost+found/
  - lost+found/
  - .nfo
  - '*.!sync'

snapraid_content_files:
  - /var/snapraid.content
  - /mnt/disk1/array/snapraid.content
  - /mnt/disk2/array/snapraid.content

snapraid_data_disks:
  - content: true
    path: /mnt/disk1
  - content: true
    path: /mnt/disk2
  - content: false
    path: /mnt/disk3

snapraid_install: true
snapraid_parity_disks:
  - content: true
    path: /mnt/parity1

snapraid_runner: true
snapraid_runner_email_address: petroplex56@gmail.com
snapraid_runner_email_pass: nXo#q28*uNzv
snapraid_runner_healthcheck_io_uuid: ''

snapraid_scrub_schedule:
  hour: 5
  weekday: 4

snapraid_sync_schedule:
  hour: 2
  minute: 30
