# ironicbadger.docker-compose-generator

# global vars
global_env_vars:
  - "PUID=1000"
  - "PGID=1001"
  - "TZ=America/New_York"
appdata_path: /opt/appdata
storage_path: /mnt/data
container_config_path: /config
container_data_path: /data

containers:
  ### Arrs 
  ###
  - service_name: radarr
    active: true
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/radarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 7878:7878
    restart: unless-stopped

  - service_name: sonarr
    active: true
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/sonarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"    
    ports:
      - 8989:8989
    restart: unless-stopped

  - service_name: prowlarr
    active: true
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - "{{ appdata_path }}/arrs/prowlarr:{{ container_config_path }}" 
    ports:
      - 9696:9696
    restart: unless-stopped

  ### Download Apps 
  ###
  - service_name: deluge
    active: true
    image: lscr.io/linuxserver/deluge:latest
    volumes:
      - "{{ appdata_path }}/downloaders/deluge:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"    
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: always

  - service_name: qbittorrent
    active: true
    image: cr.hotio.dev/hotio/qbittorrent
    volumes:
      - "{{ appdata_path }}/downloaders/qbittorrent:{{ container_config_path }}"
      - "{{ storage_path }}/torrents:{{ container_data_path }}/torrents"    
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always

  - service_name: sabnzbd
    active: true
    image: cr.hotio.dev/hotio/sabnzbd
    volumes:
      - "{{ appdata_path }}/downloaders/sabnzb:{{ container_config_path }}"
      - "{{ storage_path }}/usenet:{{ container_data_path }}/usenet"    
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always