- name: Enable high availability
  when: proxmox_ha_setup_enable_ha | bool
  block:
    - name: Enable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: true
        state: started
    - name: Enable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: true
        state: started
    - name: Enable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: true
        state: started

- name: Disable high availability
  when: proxmox_ha_setup_disable_ha | bool
  block:
    - name: Disable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: false
        state: stopped
    - name: Disable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: false
        state: stopped
    - name: Disable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: false
        state: stopped
