---
extends: default

ignore: |
  venv/
  ansible/vendor/

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: whatever
  line-length:
    max: 600
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
