---
galaxy_info:
  role_name: zfs_detect
  author: Your Name
  description: >
    Ansible role to detect existing ZFS pools, attempt import if needed, and dynamically configure disk list for pool creation.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
