# Define your variables here
proxmox_post_install_vars:
  correct_sources: "{{ 'yes' if proxmox_post_install_correct_sources else 'no' }}"
  disable_enterprise_repo: "{{ 'yes' if proxmox_post_install_disable_enterprise_repo else 'no' }}"
  enable_no_subscription_repo: "{{ 'yes' if proxmox_post_install_enable_no_subscription_repo else 'no' }}"
  correct_ceph_sources: "{{ 'yes' if proxmox_post_install_correct_ceph_sources else 'no' }}"
  add_pvetest_repo: "{{ 'yes' if proxmox_post_install_add_pvetest_repo else 'no' }}"
  disable_subscription_nag: "{{ 'yes' if proxmox_post_install_disable_subscription_nag else 'no' }}"
  enable_ha: "{{ 'yes' if proxmox_post_install_enable_ha else 'no' }}"
  disable_ha: "{{ 'yes' if proxmox_post_install_disable_ha else 'no' }}"
  update_proxmox: "{{ 'yes' if proxmox_post_install_update_proxmox else 'no' }}"
  reboot_proxmox: "{{ 'yes' if proxmox_post_install_reboot_proxmox else 'no' }}"
