---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: host
    volumes:
      - "{{ appdata_path }}/downloaders/deluge:{{ container_config_path }}"
      - /tank:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    environment:
      - PUID=1002
      - PGID=1002
      - UMASK=002
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error
    restart: always