# code: language=ansible
---
- name: Mount formatted disks using ansible-role-disk
  hosts: all
  become: yes

  pre_tasks:
    - name: Display formatted_disks variable
      debug:
        var: formatted_disks

    - name: Display mount variable
      debug:
        var: mount

  roles:
    - role: grog.package   
    - role: kevincoakley.disk
      disk_additional_packages:
        - xfsprogs

  post_tasks:
    - name: Display mounted disks
      command: df -h
      changed_when: false
      register: df_output

    - name: Show mounted disks
      debug:
        var: df_output.stdout_lines

- name: Install and configure node_exporter
  hosts: all
  become: yes
  vars:
    node_exporter_version: 1.3.1
    node_exporter_web_listen_address: "0.0.0.0:9100"

  tasks:
    - name: Install node_exporter
      include_role:
          name: prometheus.prometheus.node_exporter
      vars:
        node_exporter_version: "1.3.1"
        node_exporter_web_listen_address: "0.0.0.0:9100"

    - name: Ensure node_exporter is started and enabled 
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Check if node_exporter is accessible
      uri:
        url: "http://localhost:9100/metrics"
        method: GET
      register: node_exporter_check
      failed_when: false
      changed_when: false

    - name: Display node_exporter status
      debug:
        msg: "node_exporter is {{ 'accessible' if node_exporter_check.status == 200 else 'not accessible' }}"    

    - name: Collect node_exporter host information
      set_fact:
        node_exporter_info: "{{ node_exporter_info | default([]) + [{'ip': ansible_default_ipv4.address, 'port': 9100}] }}"

  post_tasks:

    - name: Debug node_exporter_info
      debug:
        var: node_exporter_info
      run_once: true

    - name: Debug JSON content
      debug:
        msg: "{{ {'node_exporter_hosts': node_exporter_info} | to_json }}"
      run_once: true

    - name: Write node_exporter hosts to file
      local_action:
        module: copy
        content: "{{ {'node_exporter_hosts': node_exporter_info} | to_nice_json }}"
        dest: "/tmp/node_exporter_hosts.json"
      run_once: true

    - name: Check if file exists
      stat:
        path: "/home/pofo14/node_exporter_hosts.json"
      register: file_stat
      delegate_to: localhost
      run_once: true

    - name: Display file info
      debug:
        var: file_stat
      run_once: true
  