# code: language=ansible
---
- name: Mount formatted disks using ansible-role-disk
  hosts: all
  become: true

  pre_tasks:
    - name: Display formatted_disks variable
      ansible.builtin.debug:
        var: formatted_disks

    - name: Display mount variable
      ansible.builtin.debug:
        var: mount

  roles:
    - role: kevincoakley.disk
      disk_additional_packages:
        - xfsprogs

  post_tasks:
    - name: Display mounted disks
      ansible.builtin.command: df -h
      changed_when: false
      register: df_output

    - name: Show mounted disks
      ansible.builtin.debug:
        var: df_output.stdout_lines

