---
- name: Create terraform system user for SSH access
  ansible.builtin.user:
    name: terraform
    groups: sudo
    append: true
    shell: /bin/bash
    state: present
  become: true

- name: Set authorized key for terraform user
  ansible.posix.authorized_key:
    user: terraform
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  become: true

- name: Create custom bash profile for terraform user
  ansible.builtin.copy:
    dest: /home/terraform/.bash_profile
    content: |
      # Ensure Proxmox commands are in PATH
      export PATH=$PATH:/usr/sbin:/sbin

      # Source bashrc if it exists
      if [ -f ~/.bashrc ]; then
        . ~/.bashrc
      fi
    owner: terraform
    group: terraform
    mode: '0644'
  become: true
