proxmox_api_url           = "https://pve1.flopo.retropetro.net:8006/api2/json"
proxmox_api_token_id      = "terraform-user@pve!tfe-token"
proxmox_api_token_secret  = "cb3e862a-c126-46f1-963d-ef8b8e0ab7ce"
proxmox_node              = "pve1"
truenas_root_password    = "Ch@rl!e29"
