# code: language=ansible

# grog.package

# geerlingguy.docker
docker_edition: 'ce'
docker_packages_state: present
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present
docker_users_manage: true
docker_add_repo: true
docker_users:
  - pofo14

docker_compose_generator_output_path: /opt/appdata
appdata_path: /opt/appdata
container_config_path: /config
container_data_path: /data

containers:
  ### Management - Portainer
  ###
  - service_name: portainer
    active: true
    image: portainer/portainer-ce:latest
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - "{{ appdata_path }}/management/portainer:{{ container_config_path }}"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    restart: unless-stopped

## NFS Client Mount
nfs_client_mounts:
  - src: nas.flopo.retropetro.net:/mnt/memories
    path: /mnt/ext-photos
