---
# PXE/NetbootXYZ Server configuration
pxe_server_http_root: /opt/netbootxyz/assets/
management_server_ip: "management.flopo.retropetro.net"  # Your management VM IP

pxe_server_tftp_root: /opt/netbootxyz/config/menus/

# Directory structure
pxe_server_directories:
  - path: "{{ pxe_server_http_root }}"
    mode: "0755"
  - path: "{{ pxe_server_http_root }}/preseed"
    mode: "0755"

## Ironic Badgetools Docker Compose Generator
docker_compose_generator_output_path: /opt/appdata
docker_compose_hostname: management
appdata_path: /opt/appdata
container_config_path: /config

# geerlingguy.docker
docker_edition: 'ce'
docker_packages_state: present
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

docker_add_repo: true
docker_repo_url: https://download.docker.com/linux

docker_users_manage: true
docker_users:
  - pofo14
