# code: language=ansible

# grog.package
package_list:
  - name: nfs-kernel-server
  - name: samba
  - name: smartmontools
  - name: snapraid

# geerlingguy.docker
docker_edition: 'ce'
docker_packages_state: present
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present
docker_users_manage: true
docker_add_repo: false
docker_users:
  - pofo14

# ironicbadger.docker-compose-generator
# global vars
global_env_vars:
  - "PUID=1000"
  - "PGID=1001"
  - "TZ=America/New_York"

docker_compose_generator_output_path: /opt/appdata
appdata_path: /opt/appdata
storage_path: /mnt/data
container_config_path: /config
container_data_path: /data

containers:
  ### Arrs
  ###
  - service_name: radarr
    active: true
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - "{{ appdata_path }}/arrs/radarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 7878:7878
    restart: unless-stopped

  - service_name: sonarr
    active: true
    image: lscr.io/linuxserver/sonarr:develop
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - "{{ appdata_path }}/arrs/sonarr:{{ container_config_path }}"
      - "{{ storage_path }}:{{ container_data_path }}"
    ports:
      - 8989:8989
    restart: unless-stopped

  - service_name: prowlarr
    active: true
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - "{{ appdata_path }}/arrs/prowlarr:{{ container_config_path }}"
    ports:
      - 9696:9696
    restart: unless-stopped

  ### Download Apps
  ###
  - service_name: deluge
    active: true
    image: lscr.io/linuxserver/deluge:latest
    volumes:
      - "{{ appdata_path }}/downloaders/deluge:{{ container_config_path }}"
      - /tank:/downloads
    environment:
      - PUID=1002
      - PGID=1002
      - UMASK=002
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error
    network_mode: host
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: always

  - service_name: qbittorrent
    active: true
    image: ghcr.io/hotio/qbittorrent:release-4.6.6
    volumes:
      - "{{ appdata_path }}/downloaders/qbittorrent:{{ container_config_path }}"
      - "{{ storage_path }}/torrents:{{ container_data_path }}/torrents"
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always

  - service_name: sabnzbd
    active: true
    image: ghcr.io/hotio/sabnzbd
    volumes:
      - "{{ appdata_path }}/downloaders/sabnzb:{{ container_config_path }}"
      - "{{ storage_path }}/usenet:{{ container_data_path }}/usenet"
    ports:
      - "8081:8080"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    restart: always

  - service_name: qbitmanage
    active: true
    image: ghcr.io/hotio/qbitmanage
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
      - QBT_RUN=true
      - QBT_SCHEDULE=1440
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=true
      - QBT_REM_ORPHANED=true
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=true
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=true
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
      - QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE=true
    volumes:
      - "{{ appdata_path }}/downloaders/qbitmanage:{{ container_config_path }}"
      - "{{ storage_path }}/torrents:{{ container_data_path }}/torrents"
      - "{{ appdata_path }}/downloaders/qbittorrent/data/BT_backup:/BT_backup"

  - service_name: rflood
    active: true
    image: ghcr.io/hotio/rflood
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
      - FLOOD_AUTH=false
    volumes:
      - "{{ appdata_path }}/downloaders/rflood:{{ container_config_path }}"
      - /tank:/data

## Snapraid settings
snapraid_install: false
snapraid_runner: true

snapraid_apt_package_name: snapraid
snapraid_bin_path: /usr/bin/snapraid
snapraid_force_install: false

snapraid_runner_healthcheck_io_uuid: "c1a9ad37-e308-44a0-831b-7dab804e773e"
snapraid_healthcheck_io_host: https://hc-ping.com

snapraid_runner_email_address: "{{ vault_snapraid_runner_email_address }}"
snapraid_runner_email_pass: "{{ vault_snapraid_runner_email_pass }}"
snapraid_runner_email_address_from: "{{ snapraid_runner_email_address }}"
snapraid_runner_email_address_to: "{{ snapraid_runner_email_address }}"
snapraid_runner_email_sendon: "error"
snapraid_runner_email_subject: "[SnapRAID] Status Report:"

snapraid_runner_smtp_host: smtp.gmail.com
snapraid_runner_smtp_port: 465
snapraid_runner_use_ssl: true

snapraid_config_path: /etc/snapraid.conf

snapraid_runner_path: /opt/snapraid-runner/snapraid-runner
snapraid_runner_conf: "{{ snapraid_runner_path }}.conf"
snapraid_runner_bin: "{{ snapraid_runner_path }}.py"
snapraid_runner_command_ns: "python3 {{ snapraid_runner_bin }} -c {{ snapraid_runner_conf }} \
  --no-scrub {% if snapraid_runner_healthcheck_io_uuid %}&& curl -fsS -m 10 --retry 5 -o /dev/null \
  {{ snapraid_healthcheck_io_host }}/{{ snapraid_runner_healthcheck_io_uuid }} > /dev/null{% endif %}"
snapraid_runner_command_scrub: "python3 {{ snapraid_runner_bin }} -c {{ snapraid_runner_conf }} \
  {% if snapraid_runner_healthcheck_io_uuid %}&& curl -fsS -m 10 --retry 5 -o /dev/null \
  {{ snapraid_healthcheck_io_host }}/{{ snapraid_runner_healthcheck_io_uuid }} > /dev/null{% endif %}"
snapraid_runner_scrub: true
snapraid_scrub_percent: 22
snapraid_scrub_age: 8
snapraid_runner_touch: true
snapraid_runner_delete_threshold: 250

snapraid_runner_cron_jobs:
  - { job: '{{ snapraid_runner_command_ns }}', name: 'snapraid_runner_sync', weekday: '1-6', hour: '03' }
  - { job: '{{ snapraid_runner_command_scrub }}', name: 'snapraid_runner_scrub', weekday: '0', hour: '03' }


snapraid_config_excludes:
  - '*.unrecoverable'
  - /tmp/
  - /lost+found/
  - lost+found/
  - .nfo
  - '*.!sync'

snapraid_content_files:
  - /var/snapraid.content
  - /mnt/disk1/array/snapraid.content
  - /mnt/disk2/array/snapraid.content
  - /mnt/parity1/snapraid.content

snapraid_data_disks:
  - content: false
    path: /mnt/disk0/media/
  - content: false
    path: /mnt/disk1/media/
  - content: false
    path: /mnt/disk2/media/
  - content: false
    path: /mnt/disk3/media/
  - content: false
    path: /mnt/disk4/media/
  - content: false
    path: /mnt/disk5/media/
  - content: false
    path: /mnt/disk6/media/
  - content: false
    path: /mnt/disk7/media/
  - content: false
    path: /mnt/disk8/media/
  - content: false
    path: /mnt/disk9/media/
  - content: false
    path: /mnt/disk10/media/
  - content: false
    path: /mnt/disk11/media/
  - content: false
    path: /mnt/disk12/media/

snapraid_parity_disks:
  - content: false
    path: /mnt/parity1
  - content: false
    path: /mnt/parity2

## geerlingguy.node_exporter
node_exporter_options: --collector.textfile.directory /var/lib/node_exporter/textfile_collector/

## prometheus.smartctl_exporter
smartctl_exporter_system_group: root
smartctl_exporter_system_user: root
smartctl_exporter_smartctl_interval: 10m
smartctl_exporter_smartctl_rescan: 60m

## MergerFS tigattack.mergerfs
mergerfs_install_mode: package_manager
mergerfs_mounts:
  - path: /mnt/data
    branches:
      - /mnt/disk*
    options: "defaults,nonempty,allow_other,use_ino,cache.files=partial,ignorepponrename=true,\
      moveonenospc=true,dropcacheonclose=true,minfreespace=100G,func.getattr=newest,category.create=mfs,\
      fsname=mergerfs"
  - path: /mnt/memories
    branches:
      - /mnt/ssd*
    options: "defaults,nonempty,allow_other,use_ino,cache.files=partial,ignorepponrename=true,\
      moveonenospc=true,dropcacheonclose=true,minfreespace=100G,func.getattr=newest,category.create=mfs,\
      fsname=memoryfs"
