iso_path: "/var/lib/vz/template/iso"
isos:
  - name: "OPNsense-25.1-dvd-amd64.iso"
    url: "https://mirrors.nycbug.org/pub/opnsense/releases/25.1/OPNsense-25.1-dvd-amd64.iso.bz2"
    checksum: "68efe0e5c20bd5fbe42918f000685ec10a1756126e37ca28f187b2ad7e5889ca"
    checksum_type: "sha256"
  - name: "TrueNAS-SCALE-24.10.2.iso"
    url: "https://download.sys.truenas.net/TrueNAS-SCALE-ElectricEel/24.10.2/TrueNAS-SCALE-24.10.2.iso"
    checksum: "33e29ed62517bc5d4aed6c80b9134369e201bb143e13fefdec5dbf3820f4b946"
    checksum_type: "sha256"
