# iso_path: "/var/lib/vz/template/iso"
# isos:
#   - name: "OPNsense-25.1-dvd-amd64.iso"
#     url: "https://mirrors.nycbug.org/pub/opnsense/releases/25.1/OPNsense-25.1-dvd-amd64.iso.bz2"
#     checksum: "68efe0e5c20bd5fbe42918f000685ec10a1756126e37ca28f187b2ad7e5889ca"
#     checksum_type: "sha256"
#   - name: "TrueNAS-SCALE-24.10.2.iso"
#     url: "https://download.sys.truenas.net/TrueNAS-SCALE-ElectricEel/24.10.2/TrueNAS-SCALE-24.10.2.iso"
#     checksum: "33e29ed62517bc5d4aed6c80b9134369e201bb143e13fefdec5dbf3820f4b946"
#     checksum_type: "sha256"

zfs_pool_name: "vmdata"  # <- Your data pool name
zfs_disks:
  - "/dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_0055074C188500046602"
  - "/dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_A39A074C181000024869"
  - "/dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2412270020501869"
  - "/dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2412270020502003"

# zfs_detect
zfs_detect_debug: true
zfs_detect_pools:
  - zfs01

#  Create ZFS Pool Role
create_zfs_pool_pools:
  - name: zfs01
    pool_properties:
      ashift: 12
    filesystem_properties:
      compression: lz4
    disks:
      - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_0055074C188500046602
      - /dev/disk/by-id/nvme-SPCC_M.2_PCIe_SSD_A39A074C181000024869
      - /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2412270020501869
      - /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2412270020502003

# lae.proxmox
pve_version: "8"
pve_enable_repo_pve_no_subscription: true
pve_reboot_on_kernel_update: true
pve_systemd_networkd: false

# Node Settings
pve_hostname: "pve1"
pve_domain: "flopo.retropetro.net"

interfaces_template: "{{ playbook_dir }}/templates/pve1_network_interface.j2"

# Static network configuration
pve_network:
  interfaces:
    - name: enp2s0f1
      address: "192.168.2.20/24"  # Your static IP
      gateway: "192.168.2.1"      # Your gateway
      dns:
        - "192.168.2.2"           # Your PiHole IP

  dns:
    domain: "flopo.retropetro.net"
    search: "flopo.retropetro.net"
    servers:
      - "192.168.2.2"             # Your PiHole IP

pve_reboot_timeout: 1200  # 20 minutes
ansible_connection_timeout: 180

# PVE Cluster Config
# pve_group: proxmox_nodes

# Set to "false" for standalone node initially
pve_cluster_enabled: false

# Hardware Passrough Settings
pve_pcie_passthrough_enabled: true
pve_iommu_passthrough_mode: true
pve_iommu_unsafe_interrupts: false
pve_mediated_devices_enabled: false
pve_pcie_ovmf_enabled: false
pve_pcie_ignore_msrs: false
pve_pcie_report_msrs: true

# ZFS Pool Setup
# proxmox_zfs_pools:
#   - name: "{{ zfs_pool_name }}"
#     state: present
#     disks: "{{ dynamic_zfs_disks }}"
#     properties:
#       ashift: 12
#       compression: lz4
#       atime: false

# Proxmox Storage Configuration
pve_storages:
  - name: zfs01
    type: zfspool
    content: ["images", "rootdir"]
    pool: zfs01
    sparse: true
  - name: iso
    type: dir
    path: /zfs01/iso
    content: ["iso"]
  - name: templates
    type: dir
    path: /zfs01/templates
    content: ["vztmpl"]
  - name: backup
    type: dir
    path: /zfs01/backup
    content: ["backup"]
  - name: snippets
    type: dir
    path: /zfs01/snippets
    content: ["snippets"]

pve_zfs_create_volumes:
  - zfs01/iso
  - zfs01/template
  - zfs01/backup
  - zfs01/snippets

pve_auth_debug: true

# User, Role and ACL Management for Terraform API user
pve_users:
  - name: terraform-user@pve
    password: "{{ terraform_api_password | default('changeMe123!') }}"
    email: "admin@flopo.retropetro.net"
    firstname: Terraform
    lastname: API User
    groups: ["terraform"]
    enable: true
    expire: 0
    comment: API user for Terraform automation

# System users (not PVE users - these are Linux system users)
pve_system_users:
  - name: terraform
    groups: sudo
    append: true
    shell: /bin/bash
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

pve_roles:
  - name: homelab
    privileges:
      - VM.Allocate
      - VM.Audit
      - VM.Clone
      - VM.Config.Disk
      - VM.Config.CPU
      - VM.Config.Memory
      - VM.Config.Network
      - VM.Config.Options
      - VM.Config.HWType
      - VM.Monitor
      - VM.PowerMgmt
      - VM.Snapshot
      - Datastore.Allocate
      - Datastore.AllocateSpace
      - Datastore.AllocateTemplate
      - Datastore.Audit
      - SDN.Use
      - Sys.Audit
      - Sys.Modify
      - Sys.Console

pve_groups:
  - name: terraform
    comment: "Group for Terraform automation"

pve_acls:
  - path: /
    roles: ["homelab"]
    groups: ["terraform"]
    propagate: true

# API token configuration for Proxmox
proxmox_api_user: "root@pam"
proxmox_api_password: "{{ vault_proxmox_root_password }}"

# List of API tokens to create
proxmox_api_tokens:
  - user: terraform-user
    realm: pve
    token_name: terraform
    comment: "API token for Terraform automation"
    privsep: 0  # 0 for full user permissions
  - user: terraform-user
    realm: pve
    token_name: packer
    comment: "API token for Packer automation"
    privsep: 0

# geerlingguy.ntp
ntp_manage_config: true
ntp_servers:
  - clock.sjc.he.net,
  - clock.fmt.he.net,
  - clock.nyc.he.net
