---
# Evaluate role variables and expose results for testing
- name: Set local role vars with backwards-compatible fallbacks
  ansible.builtin.set_fact:
    pve_pci_mappings_effective: "{{ pve_pci_mappings_list if (pve_pci_mappings_list | default([]) | length) > 0 else (pve_pci_mappings | default([])) }}"
    pve_pci_mappings_create_allowed: "{{ pve_pci_mappings_force_create_datacenter_cfg | default(force_create_datacenter_cfg | default(false)) }}"
    pve_pci_mappings_delegate_host: "{{ pve_delegate | default(groups['pve'] | default([inventory_hostname]) | first) }}"
  run_once: true

- name: Debug effective mappings
  ansible.builtin.debug:
    var: pve_pci_mappings_effective

- name: Debug creation allowed flag
  ansible.builtin.debug:
    var: pve_pci_mappings_create_allowed
