- name: Correct Proxmox VE sources
  when: proxmox_post_install_vars.correct_sources == 'yes'
  block:
    - name: Update sources.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian bookworm main contrib
          deb http://deb.debian.org/debian bookworm-updates main contrib
          deb http://security.debian.org/debian-security bookworm-security main contrib
        mode: '0644'
    - name: Disable non-free firmware warnings
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
        content: 'APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";'
        mode: '0644'

- name: Disable 'pve-enterprise' repository
  when: proxmox_post_install_vars.disable_enterprise_repo == 'yes'
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    content: |
      # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    mode: '0644'

- name: Enable 'pve-no-subscription' repository
  when: proxmox_post_install_vars.enable_no_subscription_repo == 'yes'
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-install-repo.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    mode: '0644'

- name: Correct 'ceph package sources'
  when: proxmox_post_install_vars.correct_ceph_sources == 'yes'
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/ceph.list
    content: |
      # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
      # deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
      # deb https://enterprise.proxmox.com/debian/ceph-reef bookworm enterprise
      # deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
    mode: '0644'

- name: Add 'pvetest' repository and set disabled
  when: proxmox_post_install_vars.add_pvetest_repo == 'yes'
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pvetest-for-beta.list
    content: |
      # deb http://download.proxmox.com/debian/pve bookworm pvetest
    mode: '0644'

- name: Disable subscription nag
  when: proxmox_post_install_vars.disable_subscription_nag == 'yes'
  block:
    - name: Create no-nag script
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/no-nag-script
        content: |
          DPkg::Post-Invoke { "dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$' || sed -i 's/data.status !== '\''Active'\''/data.status == '\''NoMoreNagging'\''/' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"; };
        mode: '0644'  # Changed from 0755 as this is a config file
    - name: Reinstall proxmox-widget-toolkit
      ansible.builtin.apt:
        name: proxmox-widget-toolkit
        state: present

- name: Enable high availability
  when: proxmox_post_install_vars.enable_ha == 'yes'
  block:
    - name: Enable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: true
        state: started
    - name: Enable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: true
        state: started
    - name: Enable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: true
        state: started

- name: Disable high availability
  when: proxmox_post_install_vars.disable_ha == 'yes'
  block:
    - name: Disable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: false
        state: stopped
    - name: Disable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: false
        state: stopped
    - name: Disable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: false
        state: stopped

- name: Update Proxmox VE
  when: proxmox_post_install_vars.update_proxmox == 'yes'
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist

- name: Enable kernel modules for PCI passthrough
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "{{ item }}"
    state: present
  with_items:
    - vfio
    - vfio_iommu_type1
    - vfio_pci
    - vfio_virqfd

- name: Add kernel parameters for IOMMU
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"'
  notify: update grub

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  changed_when: false

- name: Reboot Proxmox VE
  ansible.builtin.reboot:
  when: proxmox_post_install_vars.reboot_proxmox == 'yes'
