---
# Proxmox Post-Installation Setup Tasks
- name: Correct Proxmox VE sources
  when: proxmox_post_install_correct_sources | bool
  block:
    - name: Update sources.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian bookworm main contrib
          deb http://deb.debian.org/debian bookworm-updates main contrib
          deb http://security.debian.org/debian-security bookworm-security main contrib
        mode: '0644'
    - name: Disable non-free firmware warnings
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
        content: 'APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";'
        mode: '0644'

- name: Disable 'pve-enterprise' repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    content: |
      # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    mode: '0644'
  when: proxmox_post_install_disable_enterprise_repo | bool

- name: Enable 'pve-no-subscription' repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-install-repo.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    mode: '0644'
  when: proxmox_post_install_enable_no_subscription_repo | bool

- name: Correct 'ceph package sources'
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/ceph.list
    content: |
      # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
      # deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
      # deb https://enterprise.proxmox.com/debian/ceph-reef bookworm enterprise
      # deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
    mode: '0644'
  when: proxmox_post_install_correct_ceph_sources | bool

- name: Add 'pvetest' repository and set disabled
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pvetest-for-beta.list
    content: |
      # deb http://download.proxmox.com/debian/pve bookworm pvetest
    mode: '0644'
  when: proxmox_post_install_add_pvetest_repo | bool

- name: Disable subscription nag
  when: proxmox_post_install_disable_subscription_nag | bool
  block:
    - name: Create no-nag script
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/no-nag-script
        content: 'DPkg::Post-Invoke { "sed -i ''s/data.status !== ''Active''/false/g'' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js || true"; };'
        mode: '0644'

    - name: Reinstall proxmox-widget-toolkit
      ansible.builtin.apt:
        name: proxmox-widget-toolkit
        state: present
        force: true

- name: Enable high availability
  when: proxmox_post_install_enable_ha | bool
  block:
    - name: Enable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: true
        state: started
    - name: Enable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: true
        state: started
    - name: Enable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: true
        state: started

- name: Disable high availability
  when: proxmox_post_install_disable_ha | bool
  block:
    - name: Disable pve-ha-lrm
      ansible.builtin.systemd:
        name: pve-ha-lrm
        enabled: false
        state: stopped
    - name: Disable pve-ha-crm
      ansible.builtin.systemd:
        name: pve-ha-crm
        enabled: false
        state: stopped
    - name: Disable corosync
      ansible.builtin.systemd:
        name: corosync
        enabled: false
        state: stopped

- name: Update Proxmox VE
  when: proxmox_post_install_update | bool
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist

# Import PCI passthrough tasks
- name: Configure PCI passthrough
  ansible.builtin.import_tasks: pci_passthrough.yml

# Import fan control tasks
- name: Configure fan control
  ansible.builtin.import_tasks: fancontrol.yml

- name: Reboot Proxmox VE
  ansible.builtin.reboot:
  when: proxmox_post_install_reboot | bool
