---
- name: Install Sanoid.
  ansible.builtin.package:
    name: sanoid
    state: present

- name: Enable Sanoid timer unit.
  ansible.builtin.systemd_service:
    name: sanoid.timer
    state: started
    enabled: true

- name: Ensure Sanoid configuration directory exists.
  file:
    path: /etc/sanoid
    state: directory
    mode: 0755

- name: Configure Sanoid.
  copy:
    dest: /etc/sanoid/sanoid.conf
    content: "{{ sanoid_conf }}"
    mode: 0644
