---
- name: Debug variables
  hosts: "{{ target_hosts | default('pve1.flopo.retropetro.net') }}"
  gather_facts: false
  tasks:
    - name: Display host variables
      ansible.builtin.debug:
        msg: "iso_path is: {{ iso_path | default('Not defined') }}"
      
    - name: Show variable origin
      ansible.builtin.debug:
        msg: "All variables for this host"
        verbosity: 0

    - name: Print all host vars
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      
    - name: Dump host-specific variables
      ansible.builtin.debug:
        msg: "Host-specific variables for {{ inventory_hostname }}"
    
    - name: Check if iso_path is defined in host vars
      ansible.builtin.debug:
        msg: "iso_path in host vars: {{ hostvars[inventory_hostname].iso_path | default('Not defined in host vars') }}"
        
    - name: Check all available groups
      ansible.builtin.debug:
        msg: "Groups: {{ group_names }}"
        
    - name: Show inventory_file and inventory_dir
      ansible.builtin.debug:
        msg: 
          - "Inventory file: {{ inventory_file }}"
          - "Inventory dir: {{ inventory_dir }}"
          - "Inventory hostname: {{ inventory_hostname }}"
