---

- name: Install Apache
  hosts: all
  become: true
  tasks:

    - name: Install apache and php packages
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php packages
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: true
      when: ansible_distribution == "CentOS"
