---

- name: Install Apache
  hosts: all
  become: true
  tasks:

    - name: Update repository index
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install apache package
      # ansible.builtin.apt:
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add PHP support for apache
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: present
      when: ansible_distribution == "Ubuntu"
