---
- name: Test arensb.truenas collection access
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Try to use a module from arensb.truenas
      arensb.truenas.hostname:
        name: test-hostname
      ignore_errors: true
      register: module_test
      delegate_to: localhost
      
    - name: Show module result
      ansible.builtin.debug:
        var: module_test
