---
- name: Test arensb.truenas collection access
  hosts: localhost
  gather_facts: no
  collections:
    - arensb.truenas
  tasks:
    - name: Import custom module path
      ansible.builtin.set_fact:
        module_path: "{{ lookup('env', 'PWD') }}/roles/truenas/library"
      
    - name: Debug custom module path
      ansible.builtin.debug:
        var: module_path
      
    # Note: This just tests if the collection can be found, not if it works with the API
    - name: Find collection path
      ansible.builtin.command: python3 -c "import os; from ansible.utils.path import find_file_in_search_path; from ansible.utils.collection_loader import AnsibleCollectionConfig; print(os.path.join(AnsibleCollectionConfig.collection_paths[0], 'arensb', 'truenas'))"
      register: collection_path
      changed_when: false
      
    - name: Test if modules exist in the collection
      ansible.builtin.command: "find {{ collection_path.stdout }} -name '*.py' | grep -v __pycache__"
      register: module_list
      changed_when: false
      
    - name: Debug collection modules
      ansible.builtin.debug:
        var: module_list.stdout_lines
