---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: '${IMAGE:-geerlingguy/docker-debian12-ansible}'
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
