---
# TrueNAS hostname and domain settings
truenas_hostname: "truenas"
truenas_domain: "flopo.retropetro.net"
truenas_fqdn: "{{ truenas_hostname }}.{{ truenas_domain }}"

# Services configuration
truenas_services:
  - name: "ssh"
    enabled: true
    state: started
  - name: "nfs"
    enabled: true
    state: started
  - name: "smartd"
    enabled: true
    state: started

# NFS configuration
truenas_nfs:
  v4: true
  allow_nonroot: true

# S.M.A.R.T. configuration
truenas_smart:
  power_mode: "never"
  temp_difference: 2
  temp_info: 40
  temp_crit: 45

# API Authentication
truenas_api_key: "{{ vault_truenas_api_key | default('') }}"  # Should be defined in vault
truenas_api_protocol: "http"  # or https if SSL is configured
truenas_api_port: 80  # Default HTTP port, use 443 for HTTPS
