# code: language=ansible

formatted_disks:
    - e343df16-fadb-4ccc-82f4-2df56882718f
    - 66294621-423f-439a-bae5-8c5bc4bb2704
    - ec131b1e-ee35-4ab1-94ce-62404b13a506
    - 80d97703-71e5-417a-905c-58b17a195e94
    - 06408048-38a3-410d-94e2-c39ff9f22d6d
    - 706b2ac9-2a13-40a8-b621-94c9d7383c8a
    - b52dfe61-7047-447b-92f7-68e7796ef68d
    - abcadcad-ebd9-4b06-a061-c3a652833ea9
    - ab3a8c2d-637e-4422-85bf-6fb54af27a4c
    - e8ddd4b5-b408-4e33-9ddf-9620cfd57732
    - e8ddd4b5-b408-4e33-9ddf-9620cfd57732

mount:
    - path: "/mnt/disk1"
      src: "/dev/disk/by-uuid/{{ formatted_disks[0] }}"
      fstype: ext4
      opts: "defaults"
      state: "mounted"
    - path: "/mnt/disk2"
      src: "/dev/disk/by-uuid/{{ formatted_disks[1] }}"
      fstype: ext4
      opts: "defaults"
      state: "mounted"
    - path: "/mnt/disk3"
      src: "/dev/disk/by-uuid/{{ formatted_disks[2] }}"
      fstype: ext4
      opts: "defaults"
      state: "mounted"
    - path: "/mnt/parity1"
      src: "/dev/disk/by-uuid/{{ formatted_disks[3] }}"
      fstype: ext4
      opts: "defaults"
      state: "mounted"
    - path: "/mnt/data"
      src: "/mnt/disk*"
      fstype: fuse.mergerfs
      opts: "defaults,nonempty,allow_other,use_ino,cache.files=partial,ignorepponrename=true,\
        moveonenospc=true,dropcacheonclose=true,minfreespace=25M,func.getattr=newest,category.create=mfs,\
        fsname=mergerfs"
      state: "mounted"


package_list:
    - name: mergerfs

# #new_disk_ids:
# #- scsi-0QEMU_QEMU_HARDDISK_drive-scsi10

nfs_exports:
    - /mnt/data/ *(fsid=0,rw,no_subtree_check)

snapraid_config_excludes:
    - '*.unrecoverable'
    - /tmp/
    - /lost+found/
    - lost+found/
    - .nfo
    - '*.!sync'

snapraid_content_files:
    - /var/snapraid.content
snapraid_data_disks:
    - content: true
      path: /mnt/disk1
    - content: true
      path: /mnt/disk2
    - content: false
      path: /mnt/disk3

snapraid_install: true

snapraid_parity_disks:
    - content: true
      path: /mnt/parity1

snapraid_runner: true
snapraid_runner_email_address: petroplex56@gmail.com
snapraid_runner_email_pass: nXo#q28*uNzv
snapraid_runner_healthcheck_io_uuid: ''

snapraid_scrub_schedule:
    hour: 5
    weekday: 4

snapraid_sync_schedule:
    hour: 2
    minute: 30

storage_path: /mnt/data
