services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      # enable traefik
      - "traefik.enable=true"

      # HTTPS Router
      - "traefik.http.routers.radarr.rule=Host(`radarr.flopo.retropetro.net`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=stepca"

      - "traefik.http.routers.radarr.service=radarr"

      # service config
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

    networks:
      proxy:
        aliases:
          - radarr

    volumes:
      #- "{{ appdata_path }}/arrs/radarr:{{ container_config_path }}"
      - radarr_config:{{ container_config_path }}
      - "{{ storage_path }}:{{ container_data_path }}"
    environment:
      - PUID={{ arrs_uid }}
      - PGID={{ arrs_gid }}
      - TZ=America/New_York
    restart: unless-stopped 

# TODO: bring in any config files, if possible into a files dir and copy them to the container to bootstrap settings